build.sh.inc: Fix libiio build
First: use lower case for some header includes. Otherwise they won't be found
Second: tell cmake and Makefile we're compiling for Windows 10 otherwise the following error occurs:
dns_sd_windows.c: In function ‘open_client_sockets’:
dns_sd_windows.c:82:14: error: ‘IP_ADAPTER_ADDRESSES_XP {aka struct _IP_ADAPTER_ADDRESSES_XP}’ has no member named ‘TunnelType’
   if (adapter->TunnelType == TUNNEL_TYPE_TEREDO)
make[2]: *** [CMakeFiles/iio.dir/build.make:218: CMakeFiles/iio.dir/dns_sd_windows.c.obj] Error 1

,which happens because 'struct _IP_ADAPTER_ADDRESSES_XP' is defined differently on older windows versions.

Signed-off-by: Dan Nechita <dan.nechita@analog.com>